### PR TITLE
Fixed seach bar collapse

### LINKED ISSUE #1807: Caluculators not collapsing after searching
## **Describe the bug**

- if we search a calculator while have a calculator on screen. It slides upon that calculator.

## **Screenshots**

Screenshot from 2021-05-06 17-12-57

### PR DESCRIPTION
**Pull request by shubhdeep123**
fix #1807 

#### Describe the changes you've made
Created a function to close previously opened calculator.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by shubhdeep123** [comment]
@sairish2001 please have a look at the changes I have made

**Review by sairish2001 — APPROVED** [review]

**Comment by shubhdeep123** [comment]
@sairish2001 do this PR require anymore changes?

**Comment by sairish2001** [comment]
> @sairish2001 do this PR require anymore changes?

No, everything seems fine

**Comment by shubhdeep123** [comment]
> > @sairish2001 do this PR require anymore changes?
> 
> No, everything seems fine

So can you merge this PR?

**Comment by shubhdeep123** [comment]
@sairish2001 can re-review this PR it is ready to merge.

**Pull request merged**
