### PR TITLE
tertradecagon calculator

### LINKED ISSUE #1634: Tetradecagon calculator
Hi i would like to add tetradecagon calculator

### PR DESCRIPTION
**Pull request by khareyash05**
fix #1634 
Added tetragon calculator

### CODE REVIEW

**Comment by khareyash05** [comment]
@sairish2001 Could you pls help me as to why cant i not resolve the conflicts?

**Review by sairish2001 — APPROVED** [review]

**Comment by sairish2001** [comment]
I am also wondering, for some of the PR's the resolve conflicts button is disabled

**Comment by khareyash05** [comment]
@sairish2001 Shall i make a new PR then?

**Comment by sairish2001** [comment]
If you can, then go ahead

**Comment by abhijeet141** [comment]
@khareyash05 Once check your file changed it is showing you have added tridecagon and tetradecagon both i think that is the reason for conflicts

**Comment by khareyash05** [comment]
@abhijeet141 I created the new branch inside my older branch . I too am thinking the same

**Comment by abhijeet141** [comment]
> @abhijeet141 I created the new branch inside my older branch . I too am thinking the same
> So shall i delete the tridecagon commit ?

Yes and you can first checkout to main and then create a new branch to avoid this conflict :)

**Comment by khareyash05** [comment]
@sairish2001 Created a new PR

**Pull request closed without merging**
