### PR TITLE
GST Calculator Added

### PR DESCRIPTION
**Pull request by ShrutiOmer**
## Related Issue

- Added a new GST Calculator in General Maths
Closes: #944 

## Checklist
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
image

### CODE REVIEW

**Comment by sairish2001** [comment]
Instead of adding formula used, provide step wise solutions, to it

**Comment by ShrutiOmer** [comment]
Okk, I will do it

**Comment by ShrutiOmer** [comment]
I have done the changes , please review it.

**Comment by sairish2001** [comment]
Instead of creating multiple `<p>` tags
you can concatenate, a single string
like
```
var temp=' ';
temp+= "Hello";
temp+= "\n";
temp+= "World";

document.getElementById('....').innerHTML=temp;

```

**Comment by ShrutiOmer** [comment]
I have removed <p> tags and used only 4 .
Please review it.

**Review by sairish2001 — APPROVED** [review]
Great Work :)

**Pull request merged**
