### PR TITLE
Converted About Info Into a card format

### LINKED ISSUE #1400: UI Change in About info section
## Proposal

I would like to change the UI of about section as it doesn't have much clearly visible color.
I would like to make it like a card with white and black contrast.

- **Currently** :
Screenshot from 2021-04-25 14-46-41

### PR DESCRIPTION
**Pull request by shubhdeep123**
## Related Issuse
- Color scheme of about info section was not clearly visible.
fix #1400 

#### Describe the changes you've made

- I have changed the UI of About Info section and it is now in the form of CARD 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
- **Updated** : 

Screenshot from 2021-04-25 14-51-37
Screenshot from 2021-04-25 14-51-40

### CODE REVIEW

**Review by sairish2001 — CHANGES_REQUESTED** [review]
It's not looking too good, try making borders round, and adding some inner or outer shadows

**Comment by shubhdeep123** [comment]
@sairish2001  should I just keep appblack color on bg or should it change according to the light and dark mode?

**Comment by sairish2001** [comment]
Yes Change according to mode

**Comment by shubhdeep123** [comment]
@sairish2001 lighmode class was not add to number fact div and about section. i fixed it and now this is how it looks, if you want any changes let me or else I can update the branch 

Screenshot from 2021-04-26 14-12-18
Screenshot from 2021-04-26 14-12-23

**Review by sairish2001 — CHANGES_REQUESTED** [review]
Don't Change color, like in light mode you put Black background and vice-versa in dark mode.

**Comment by shubhdeep123** [comment]
@sairish2001 so which colour suits better for background of about info? Black or pink?

**Comment by sairish2001** [comment]
> @sairish2001 so which colour suits better for background of about info? Black or pink?

Same as Background, as we are planning to change the whole UI, so remain as it is same as background

**Comment by shubhdeep123** [comment]
@sairish2001  please have a look at these do they look fine?

Screenshot from 2021-04-27 22-35-08

Screenshot from 2021-04-27 22-35-03

**Comment by sairish2001** [comment]
Change background color to dark in dark mode

**Comment by shubhdeep123** [comment]
Done

**Review by sairish2001 — APPROVED** [review]

**Comment by shubhdeep123** [comment]
@sairish2001  I would love to work on the UI for the platform!

**Pull request merged**
