### PR TITLE
add area of sector

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #1076 
Added area of sector when user types angle and radius of sector

### CODE REVIEW

**Comment by shrey27tri01** [comment]
@khareyash05 Can you provide some screenshots showing the changes you did?

**Comment by khareyash05** [comment]
image
@shrey27tri01 @sairish2001

**Review by sairish2001 — CHANGES_REQUESTED** [review]
Do add this under shapes Calculator

**Comment by khareyash05** [comment]
@sairish2001 I have to move it to shapes calculator right?

**Comment by sairish2001** [comment]
> @sairish2001 I have to move it to shapes calculator right?

yes

**Comment by khareyash05** [comment]
@sairish2001 Shifted to shapes calculator and resolved conflicts

**Comment by khareyash05** [comment]
image

**Review by sairish2001 — APPROVED** [review]
Great Work :)

**Pull request merged**
