### PR TITLE
Added Mathematical Reasoning section

### PR DESCRIPTION
**Pull request by bitaashna**
## Related Issuse
#574 

Closes: #574 

#### Describe the changes you've made
Added formulae and terms related to mathematical reasoning such as:

- Table for basic logical connections
- Tautology and Contradiction
- converse
- Contrapositive
- negation
- Some other important terms

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
Screenshot from 2021-03-28 16-45-02
Screenshot from 2021-03-28 16-44-59
Screenshot from 2021-03-28 16-44-55
Screenshot from 2021-03-28 16-44-51
Screenshot from 2021-03-28 16-44-48
Screenshot from 2021-03-28 16-44-46
Screenshot from 2021-03-28 16-44-44
Screenshot from 2021-03-28 16-44-40
Screenshot from 2021-03-28 16-44-35

### CODE REVIEW

**Comment by bitaashna** [comment]
@sairish2001 Please review it!

**Review by sairish2001 — APPROVED** [review]
Well Done :)

**Comment by bitaashna** [comment]
@sairish2001 Please revert back my PR.I think because of some issues in my PR site is not working properly.I will make a new PR after solving it.Sorry for the inconvenience caused.

**Comment by sairish2001** [comment]
Can you please tell, Which issue persists in the site?

**Comment by bitaashna** [comment]
Some Participants have messaged me and told me that after merging this PR some part of the site is not working

**Comment by sairish2001** [comment]
Now PR can't be reverted. I am getting an error, because I already merged many PR's after yours

**Comment by bitaashna** [comment]
Sorry for the inconvenience,but we can do one thing I will create a PR ,after correcting it all U can merge that and don't label it as gssoc and no need to give any labels

**Comment by sairish2001** [comment]
Go ahead

**Comment by sairish2001** [comment]
Will it be done by today?

**Comment by bitaashna** [comment]
I don't know,it's a time consuming work,taking a lot of time to go through the whole code and check the bug in it.

**Comment by bitaashna** [comment]
I'll try to complete it by midnight

**Pull request merged**
