### PR TITLE
Alligned List + Fixed all bugs

### LINKED ISSUE #1331: List not alligned properly
## **Describe the bug**

- List are not alligned properly

## **Screenshots**

- 
image

List should be 

image

### PR DESCRIPTION
**Pull request by abhijeet141**
## Related Issuse

- Info about Issue or bug

fix #1331  #1367 

#### Describe the changes you've made

Extra div was closed so removed that and there was some bug in nth term of HP so resolved that

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

## Screenshots
image
image

### CODE REVIEW

**Review by sairish2001 — CHANGES_REQUESTED** [review]
I think by mistake you deleted the N term of HP progression button

**Comment by abhijeet141** [comment]
> I think by mistake you deleted the N term of HP progression button

Actually it was repeated two times in the code so deleted one

**Comment by abhijeet141** [comment]
@sairish2001 
image

**Review by sairish2001 — APPROVED** [review]
Great work :)

**Pull request merged**
