### PR TITLE
RECTIFIED - Inappropriate promt in LCM/HCF/Factors 

### LINKED ISSUE #796: Inappropriate promt in LCM/HCF/Factors
## **Describe the bug**

- In case of entering negative numbers "Enter numbers only" prompt is displayed instead of "Only positive values allowed"

## **Possible solution**

- Adding appropriate check over negative numbers to avoid faulty prompt

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
Attention - Inappropriate prompt given for negative values entered in LCM-HCF-Factors

### PR DESCRIPTION
**Pull request by SarthakKeshari**
## Related Issuse

- In case of entering negative numbers "Enter numbers only" prompt is displayed instead of "Enter positive numbers only"

fix #796 

#### Describe the changes you've made

Added appropriate check over negative numbers to avoid faulty prompt

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
Attention - Inappropriate prompt given for negative values entered in LCM-HCF-Factors|RECTIFIED - Inappropriate prompt given for negative values entered in LCM-HCF-Factors

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
Issue has been resolved

**Comment by SarthakKeshari** [comment]
@sairish2001, Kindly look into this. I don't know why one of the checks failed.

**Comment by AB-san** [comment]
> @sairish2001, Kindly look into this. I don't know why one of the checks failed.

image

you have extra line of code , the checks are failing there

**Review by sairish2001 — APPROVED** [review]

**Comment by abhijeet141** [comment]
@SarthakKeshari I think by mistake you have added these lines of code again because of which again no calculators are working
image
image
@sairish2001 please look into this

**Comment by SarthakKeshari** [comment]
@abhijeet141 This code was already present. I have just accepted the incoming changes

> @SarthakKeshari I think by mistake you have added these lines of code again because of which again no calculators are working
> image
> image
> @sairish2001 please look into this

**Comment by abhijeet141** [comment]
> @abhijeet141 This code was already present. I have just accepted the incoming changes
> 
> > @SarthakKeshari I think by mistake you have added these lines of code again because of which again no calculators are working
> > image
> > image
> > @sairish2001 please look into this

but now it is added again in the code

**Pull request merged**
