### PR TITLE
Date

### PR DESCRIPTION
**Pull request by satyampgt4**
## Related Issuse

Date calculator

Closes: #209
#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by shrey27tri01 — APPROVED** [review]
Awesome work on this!

**Comment by satyampgt4** [comment]
conflict is resolved

**Comment by sairish2001** [comment]
Kindly update your code, it's still creating conflicts @satyampgt4

**Comment by sairish2001** [comment]
Make new PR ,with required changes

**Pull request merged**
