### PR TITLE
var added to variables

### PR DESCRIPTION
**Pull request by AmjadNoor**
## Related Issuse
#1550 

fix #[issue number that will be closed through this PR]

## Description
We can add `var` or `let` because of global variable but I prefer `var` for this project because `var` is used everywhere for global variable.
## Checklist

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| 
Screenshot_2021-05-01-05-34-57-60
 | 
Screenshot_2021-05-01-05-51-03-60
 |

### CODE REVIEW

**Review by sairish2001 — CHANGES_REQUESTED** [review]
This PR is showing changes in 100+ of files, Kindly check this.

**Comment by AmjadNoor** [comment]
> This PR is showing changes in 100+ of files, Kindly check this.

Because I updated my fork repo even to upstream without using git command.

**Comment by sairish2001** [comment]
Kindly Fix it, as it is more likely give rise to bugs

**Comment by AmjadNoor** [comment]
> Kindly Fix it, as it is more likely give rise to bugs

Ok, let's close this pull request. I want to create a new pull request of the issue #1550

**Pull request closed without merging**
