### PR TITLE
Automatic Scrolling of Calculator

### PR DESCRIPTION
**Pull request by Sukriti-sood**
## Related Issuse

Scroll calculator automatically on toggle down  #95

#### Describe the changes you've made

Now , If Any Topic is opened and if we toggle calculator if it is open than our window smoothly scroll to the calculator .

### CODE REVIEW

**Review by sairish2001 — CHANGES_REQUESTED** [review]
Remove the alert popup

**Review by sairish2001 — COMMENTED** [review]
Your code is not updated, hence will create Problem after merging. So make changes to updated codebase.

**Comment by Sukriti-sood** [comment]
> Your code is not updated, hence will create Problem after merging. So make changes to updated codebase.
I am facing problem while pulling changes from upstream to my local branch and then pushing to remote repo

**Comment by Sukriti-sood** [comment]
> Your code is not updated, hence will create Problem after merging. So make changes to updated codebase.

I am facing problem while pulling changes from upstream to my local branch and then pushing to remote repo

**Pull request closed without merging**
