### PR TITLE
Laplace transforms and properties added

### PR DESCRIPTION
**Pull request by RaveenaBhasin**
## Related Issue: #500 
I have added all the important laplace transforms and properties used for laplace transformations

### CODE REVIEW

**Comment by shrey27tri01** [comment]
@RaveenaBhasin  Could you please add some screenshots showing the changes? After that, we can resolve the merge conflicts :)

**Comment by RaveenaBhasin** [comment]
Screenshot (1608)
Screenshot (1609)

**Comment by RaveenaBhasin** [comment]
@shrey27tri01 @sairish2001 Please review it

**Review by shrey27tri01 — APPROVED** [review]
Great work!

**Pull request merged**
