### PR TITLE
Fixed Issue Number #585 (Some buttons are not working)

### PR DESCRIPTION
**Pull request by abhijeet141**
Closes: #[issue number that will be closed through this PR]
Issue Number #585 
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by sairish2001 — COMMENTED** [review]
There are no such changes in `index.html` file you made which will resolve this issue. Have you tested? is it working fine?

**Comment by abhijeet141** [comment]
> There are no such changes in `index.html` file you made which will resolve this issue. Have you tested? is it working fine?

Yes one div was not closed and it was working fine

**Comment by abhijeet141** [comment]
> > There are no such changes in `index.html` file you made which will resolve this issue. Have you tested? is it working fine?
> 
> Yes one div was not closed and it was working fine

But today again someone have repeated that mistake and now all buttons ae not working

**Review by sairish2001 — APPROVED** [review]
Well Done :)

**Pull request merged**
