### PR TITLE
Solved Issue Number #435 (To add more Formulae in the section Indefinite Integration Formulae as many formulae are missing)

### PR DESCRIPTION
**Pull request by abhijeet141**
Closes: #[issue number that will be closed through this PR]
Issue Number #435 

#### Describe the changes you've made
Added some standard formula
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by shrey27tri01** [comment]
Could you please add some screenshots showing the changes you made? That will be useful for future reference :)

**Comment by abhijeet141** [comment]
Yes Sure
image

**Comment by abhijeet141** [comment]
Yes Sure 
Original
image
Updated
image

**Review by shrey27tri01 — APPROVED** [review]
Awesome work on this!

**Comment by abhijeet141** [comment]
> Awesome work on this!

Thanks 🙂

**Pull request merged**
