### PR TITLE
Corrected the Wrongly Wriiten formula of CSA and TSA of hollow sphere

### PR DESCRIPTION
**Pull request by bitaashna**
## Related Issuse
#567 
Closes: #567 

#### Describe the changes you've made
Corrected the Wrongly Wriiten formula of CSA and TSA of hollow sphere
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

Screenshot from 2021-03-28 02-50-00

### CODE REVIEW

**Comment by bitaashna** [comment]
@sairish2001 Please review it!

**Review by sairish2001 — COMMENTED** [review]
What are the changes you made? as in files there are no such changes as described

**Comment by bitaashna** [comment]
I have corrected the formula,It was written wrongly previously

**Comment by sairish2001** [comment]
Check again the files in this PR

**Comment by bitaashna** [comment]
ok.,I will check!

**Comment by bitaashna** [comment]
@sairish2001 Please check it now!

**Review by sairish2001 — APPROVED** [review]
Well Done :)

**Pull request merged**
