### PR TITLE
Made a navbar

### LINKED ISSUE #1597: Add background for toggle
## Problem:-

Currently In Mobile View , On Scrolling Toggle button and the text are giving bad look or  getting overlapped.

### I thought of two Solutions:-

1.  Add a parent to toggle button like nav-bar (fixed) and adding background to that like this...
 
7839366-d0a881fddbdc3c34512c223de168f3e5 (1)

2. Add fixed nav bar also with options favourite and calc icon this will solve one more issue like if one has opened nav bar and if want to close than no need to go to top .

### PR DESCRIPTION
**Pull request by Sukriti-sood**
## Related Issuse
Improvement with toggle and navbar

fix #1597

#### Describe the changes you've made

Screenshot from 2021-05-09 14-02-56

### CODE REVIEW

**Review by sairish2001 — CHANGES_REQUESTED** [review]
Instead of creating own Nav bar, i would suggest you to implement Bootstrap's navbar

**Comment by Sukriti-sood** [comment]
> Instead of creating own Nav bar, i would suggest you to implement Bootstrap's navbar

@sairish2001  I didn't created any Nav bar , there was a form-group , I just give it a width and Padding  and ,If you want to add Bootstrap Navbar , I will do.

**Comment by sairish2001** [comment]
> > Instead of creating own Nav bar, i would suggest you to implement Bootstrap's navbar
> 
> @sairish2001  I will do.

Wait, Kindly don't add any navbar, till date, i would suggest you to remove the background color from the existing changes @Sukriti-sood

**Comment by sairish2001** [comment]
> After Removing background color
> Screenshot from 2021-05-09 21-27-14
> 

Actually this is also not looking good, remain it as it is. We are planning to change the UI, will be covered. I respect your Contribution but I have to close this PR.

**Pull request closed without merging**
