### PR TITLE
Fixed search bar bug

### PR DESCRIPTION
**Pull request by Abhisheka394**
## Related Issuse

- Search bar used to remain open only when we hover on it, while typing it closes automatically if we won't hover on it

Closes: #293 

#### Describe the changes you've made

Changed the CSS file to stop the search bar from closing.

## Checklist:

- [ X] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have made corresponding changes to the documentation.
- [ X] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
Original Screenshot without hover
search bar bug
Screenshot (103)
Screenshot (104)
<b>updated screenshot without hover</b> |

### CODE REVIEW

**Comment by sairish2001** [comment]
now it remains always open?

**Comment by Abhisheka394** [comment]
Yes

**Review by sairish2001 — APPROVED** [review]
Well Done!

**Review by sairish2001 — COMMENTED** [review]
But the task is that it should not close when there's text inside the search bar. When it's empty the animation must be there.

Make required changes and make a PR

**Comment by Abhisheka394** [comment]
Ok, I'll make a PR after making the appropriate changes to the code.

**Pull request merged**
