### PR TITLE
Added the logo of MakesMathEasy at the center of the page

### PR DESCRIPTION
**Pull request by gritika18**
## Related Issue
- The issue was that the website looks blank as it has only the search bar, and the number fact.

Closes: #90 

#### Describe the changes you've made
In order to remove the issue I had created, I added the logo of MakesMathEasy at the top center of the page. I wanted to make it look like google.

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
Updated
Screenshot
After changing mode
Screenshot on mode change

### CODE REVIEW

**Review by shrey27tri01 — APPROVED** [review]
The merge conflict has been resolved. This PR is good to go :)

**Comment by gritika18** [comment]
Thankyou @shrey27tri01                                                                                                                                                                           I wanted to ask if I have to do anything else after making PR? This is my first PR, I don't have any idea of what to do next.

**Comment by shrey27tri01** [comment]
@gritika18 There's nothing more you need to do after making the PR. It has been approved by me, and once other mentors or the project admin approves it, it will be merged to the main project :)

**Comment by gritika18** [comment]
> @gritika18 There's nothing more you need to do after making the PR. It has been approved by me, and once other mentors or the project admin approves it, it will be merged to the main project :)

Okay, thankyou :)

**Pull request closed without merging**
