### PR TITLE
Added bot for auto-message for merged pr

### PR DESCRIPTION
**Pull request by AB-san**
Added a auto-bot-message for each contributor after their pr is successfully merged

Closes: #[issue number that will be closed through this PR]

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
An example of the auto-bot-message

image

### CODE REVIEW

**Review by sairish2001 — APPROVED** [review]
Well Done :)

**Comment by sairish2001** [comment]
I merged alot of PR's but the message is not Showing, also the Git-Guardian checks are getting failed

**Comment by AB-san** [comment]
> I merged alot of PR's but the message is not Showing, also the Git-Guardian checks are getting failed

image

no actually the auto-bot-message is only getting failed 
Please give me some time I am trying to find why its getting failed

**Comment by sairish2001** [comment]
Error adding autoresponse: Resource not accessible by integration

this is the error, I am getting

**Comment by AB-san** [comment]
> Error adding autoresponse: Resource not accessible by integration
> 
> this is the error, I am getting

Yes , it means the resources that i used to make that bot is not useful enough , I am searching for new resources !!

**Pull request merged**
