### PR TITLE
ADDED - Calculator to conic section and conflict resolved

### PR DESCRIPTION
**Pull request by SarthakKeshari**
## Related Issuse

- There was no calculator for equations of parabola, ecllipse and hyperbola

Closes: #497 

#### Describe the changes you've made

I have added a conicSolve.js file with all the logic for the conic section items, added calculator UI with index.html and added few lines to style.css to get required styling

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
Calculator was not present| ADDED - Calculator to conic section 1|
Calculator was not present|ADDED - Calculator to conic section 2|
Calculator was not present| ADDED - Calculator to conic section 3|
Calculator was not present| ADDED - Calculator to conic section 4|
Calculator was not present| ADDED - Calculator to conic section 5|
Calculator was not present| ADDED - Calculator to conic section 6|
Calculator was not present| ADDED - Calculator to conic section 7|
Calculator was not present|ADDED - Calculator to conic section 8|

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@sairish2001 Sir I have added the required functionality and functions but I am unable to understand this conflict. Please help

**Comment by sairish2001** [comment]
Don't worry, I will resolve it by myself

**Comment by SarthakKeshari** [comment]
Sure sir... Waiting for conflicts to be resolved and branch to be merged. Excited!!

**Comment by SarthakKeshari** [comment]
Sir @sairish2001  I am unable to make contribution after this conflict may you tell me a way out
image

**Comment by SarthakKeshari** [comment]
@sairish2001 Sir I have resolved the conflict it was occuring due to unwanted statements in last line and 8th last line of index.html

**Review by sairish2001 — APPROVED** [review]
Well Done :)

**Comment by SarthakKeshari** [comment]
Thankyou sir

**Pull request merged**
