### PR TITLE
fourier-series is  added

### LINKED ISSUE #177: [GSSoC '21] Adding Fourier Series
Hello,
I want to add Fourier Series in the calculus section as part of my GSSoC participation.
Thank you

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issuse

fourier-series is  added

fix #177 

#### Describe the changes you've made

I have added the fourier series 
## Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

Makes Math Easy - Google Chrome 21-04-2021 23_38_33
9b84-a2dd2b219a8a.png)
Makes Math Easy - Google Chrome 21-04-2021 23_38_46

### CODE REVIEW

**Comment by Ankita297** [comment]
@sairish2001  Please review my PR .

**Review by sairish2001 — APPROVED** [review]

**Comment by Ankita297** [comment]
@sairish2001 the issue has level 3 label ? If you can add it .

**Comment by Ankita297** [comment]
@sairish2001 the issue has level 3 label ? If you can add it .

**Comment by sairish2001** [comment]
Actually the issue, was to add Fourier Series Calculator,but you added Documentation

**Comment by Ankita297** [comment]
Okay @sairish2001 .

**Pull request merged**
