### PR TITLE
Fixed the searchbar

### PR DESCRIPTION
**Pull request by gnikita432**
## Related Issuse

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
search bar and other content  are not overlapping now

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
mathissue2
mathissue1

### CODE REVIEW

**Comment by sairish2001** [comment]
But it still stays at back, at fixed position. It should not stay always at same position. It should scroll on page scroll.

**Comment by gnikita432** [comment]
Yes It is scrolling on the page scroll.

**Review by sairish2001 — COMMENTED** [review]
Great Work!

**Comment by gnikita432** [comment]
Thank you

**Pull request merged**
