### PR TITLE
strain calculator added

### PR DESCRIPTION
**Pull request by shrishti-c**
Closes: #1148 

My last PR merged two issues. That's why creating a PR regarding that issue. :)
## Related Issue
Screenshot (177)
Screenshot (178)
Screenshot (179)
Screenshot (180)

- Info about Issue or bug

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.

### CODE REVIEW

**Comment by sairish2001** [comment]
Where you made the changes, as it is showing only two lines of changes in this PR

**Comment by shrishti-c** [comment]
Screenshot (188)
@sairish2001 Actually when I made hydrostatic calculator after making PR for that, I started working on Strain calculator. But then PR got merged after pushing Strain Calculator. You can verify that from the hydrostatic PR.  But I won't be getting marks for that issue if PR don't get merged. So, I made PR referencing to that issue.

**Comment by shrishti-c** [comment]
Screenshot (189)

@PR- 1178 I have mentioned regarding this in this PR also and also on discord before.

**Comment by shrishti-c** [comment]
@sairish2001

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
