### PR TITLE
ENHANCED - Show steps for calculation in 7s and 8s complement

### PR DESCRIPTION
**Pull request by SarthakKeshari**
## Related Issuse

- No steps were shown for 7's and 8's complement calculation

Closes: #773 

#### Describe the changes you've made

Added required functionality to code base by making changes to index.html and logicjavascript.js

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
Attention - Show Steps for 7s and 8s complement calculation|RECTIFIED - Show Steps for 7s and 8s complement calculation

### CODE REVIEW

**Review by sairish2001 — APPROVED** [review]
Great

**Comment by SarthakKeshari** [comment]
Sir @sairish2001,
There were just extra blank spaces due to my multiple commit issue. I have resolved it successfully

**Comment by SarthakKeshari** [comment]
Sir @sairish2001,
It is showing so since in my last generated PR all this previous changes have been accomodated. So the changes that I had made for this PR have been commited together with my StatsCal commit in a single bundle. So these commits are show 0 addition and 1 deletion.
I request you to garde this PR as accepted since the changes I had made to this have been commited through my morning's PR named StatsCal rendering this PR as useless.

Thankyou.

**Comment by SarthakKeshari** [comment]
Here is the code proof as can be seen under commit tab on this page

image

**Pull request merged**
