### PR TITLE
 Placing the Prime Numbers section below search bar and modifying the code.

### LINKED ISSUE #1324: Prime numbers section is very close to the footer and it is not working.
## **Describe the bug**
The prime numbers section appears very close to the footer and Primality test and primes until entered number is not working.

## **Possible solution**
The prime numbers section is appearing very close to the footer rather than below the search bar. I would like to fix that and
I would like to modify the code for the Primality test and primes till entered no. Please assign this to me.

## **Screenshots**

prime1
prime02

### PR DESCRIPTION
**Pull request by Ananya-Misra**
## Related Issues

Prime Section is very close to the footer and the code for the prime numbers section is not working.
Fix #1324 

#### Describe the changes you've made
The prime section appears below the search bar and is working fine.
I changed the code for prime till n terms to a simpler one and added punctuations to the primality test code.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
| prime1 | <b>prime 03</b>|
| prime02 |<b>prime 04</b>|

### CODE REVIEW

**Comment by Ananya-Misra** [comment]
@sairish2001 Please review my code.

**Review by sairish2001 — APPROVED** [review]

**Comment by Ananya-Misra** [comment]
@sairish2001 should I close this PR?

**Comment by Ananya-Misra** [comment]
Hii @sairish2001 since you have approved my PR for this issue, is there a reason why you are not merging it? I request you to let me know the reason.

**Comment by sairish2001** [comment]
There are slme conflicts in this PR, soon I will merge it after resolving the conflicts

**Comment by Ananya-Misra** [comment]
Ok,  thanks for the clarification.

**Pull request merged**
