### PR TITLE
Algebraic Identities added

### PR DESCRIPTION
**Pull request by RaveenaBhasin**
Added all the important algebraic identities under the linear algebra section

### CODE REVIEW

**Review by sairish2001 — APPROVED** [review]
Well Done!
Thanks for your contribution

**Comment by sairish2001** [comment]
Kindly update your code, as outdated codebase is creating problems

**Comment by sairish2001** [comment]
@RaveenaBhasin

**Comment by RaveenaBhasin** [comment]
> Kindly update your code, as outdated codebase is creating problems

I didn't understood meaning of  Outdated code. Please explain.

**Comment by RaveenaBhasin** [comment]
How I have to update my code?

**Comment by sairish2001** [comment]
Reclone

**Comment by RaveenaBhasin** [comment]
I have to reclone and make the PR again right?

**Comment by sairish2001** [comment]
Yes

**Comment by sairish2001** [comment]
also, for your recent PR do the same, as when PR's got merged new features added into the project, so you need to always keep your codebase updated.

**Comment by RaveenaBhasin** [comment]
@sairish2001 my code is completely updated could you please check the PR#284

**Pull request merged**
