### PR TITLE
Fixed Issue Number #1041 (Two scroll bar in properties of probability section)

### PR DESCRIPTION
**Pull request by abhijeet141**
## Related Issuse

- Two scroll bar in some section

fix #[issue number that will be closed through this PR]
Issue Number #1041 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| 
image
 | <b>
image
  </b> |

### CODE REVIEW

**Review by sairish2001 — CHANGES_REQUESTED** [review]
Instead of adding overflow hidden to body and html, add to probability div only

**Comment by abhijeet141** [comment]
> Instead of adding overflow hidden to body and html, add to probability div only

Actually in many other section also there are two scroll bar

**Review by sairish2001 — CHANGES_REQUESTED** [review]
use overflow:auto;
instead

**Comment by abhijeet141** [comment]
> use overflow:auto;
> instead

Okay

**Comment by abhijeet141** [comment]
> use overflow:auto;
> instead

@sairish2001 by adding overflow:auto there is no changes the additional scroll bar remains there

**Comment by abhijeet141** [comment]
@sairish2001 please check this the bug was due to this line
image

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
