### PR TITLE
remove duplicate identities

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #338 
Removed duplicate algebraic identities from linear algebra

### CODE REVIEW

**Comment by khareyash05** [comment]
@sairish2001 Have a look

**Review by shrey27tri01 — APPROVED** [review]
Great work!

**Comment by shrey27tri01** [comment]
I have resolved the merge conflicts that were arising. This PR is ready to get merged.

**Comment by khareyash05** [comment]
@shrey27tri01 thanx

**Pull request merged**
