### PR TITLE
Fixed the shapes calculation part

### LINKED ISSUE #1294: Some shapes calculation part is not working
## **Describe the bug**

Below I have mentioned exact shapes whose calculation part is not showing up. I would like to work on this issue. Please assign this to me under GSSoC. 

- Cone
- Sphere
- Hollow sphere
- Hemisphere
- Torus
- Pentagonal hexagonal octagonal pyramid
- Octahedron

### PR DESCRIPTION
**Pull request by madihamallick**
## Related Issue

- Info about Issue or bug

fix #1294 

#### Describe the changes you've made

All the shapes are working now.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by khareyash05** [comment]
@madihamallick its against the rules of open source that a PR is created before assignment 
And also I had created the issue before so I think you should close the issue

**Comment by Ankita297** [comment]
@madihamallick have you added any code as it shows you have added and deleted some blank lines .

**Comment by madihamallick** [comment]
> @madihamallick have you added any code as it shows you have added and deleted some blank lines .

Hi @Ankita297  how does that even bother you. And why do I even explain you **what changes I made**. And yes, to resolve any bug you don't always have to **"add codes"**.  They maybe some missing brackets or semicolons.

Just know that the issue you created #1357 will be resolved when this PR gets merged. I have provided screenshot too, for your reassurance :)

**Comment by Ankita297** [comment]
@madihamallick  I am sorry . I don't mean to be offensive . But i was just curious so i asked .
Sorry again .

**Comment by madihamallick** [comment]
> @madihamallick I am sorry . I don't mean to be offensive . But i was just curious so i asked .
> Sorry again .

It's totally fine. Not your fault :)

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
