### PR TITLE
power operator added in calculator

### PR DESCRIPTION
**Pull request by zhcet19**
## Related Issuse

- Info about Issue or bug

Resolved issue #684 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot pic1pic3

</b> |

### CODE REVIEW

**Comment by zhcet19** [comment]
On clicking More it turns less while ( turns into ),in place of ) i have added power operator

**Comment by zhcet19** [comment]
@sairish2001  please review this pr

**Review by sairish2001 — CHANGES_REQUESTED** [review]
I would like you to add a row below 1st row  and make required changes. as shown in image.
Also no need to change contents of Row on clicking **more**
Image

This is an edited image

**Comment by zhcet19** [comment]
I will be making a fresh pr and will make the requested change

**Pull request closed without merging**
