### PR TITLE
add centroid calculator

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #1212 
Added centroid calculator

### CODE REVIEW

**Comment by RaveenaBhasin** [comment]
@khareyash05 I think you have added this centroid calculator in between the parallel line checker calculator by mistake.
Screenshot (1838)_LI
The lines which are in box are a part of parallel line calculator.

**Comment by khareyash05** [comment]
Ohhh sorry sorry @RaveenaBhasin

**Comment by khareyash05** [comment]
@sairish2001 Resolved merge conflicts

**Review by sairish2001 — APPROVED** [review]

**Comment by khareyash05** [comment]
@sairish2001 REsolved merge conflicts

**Pull request merged**
