### PR TITLE
inverse,period of functions

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #611 
Added inverse and period of functions

### CODE REVIEW

**Review by sairish2001 — APPROVED** [review]

**Comment by khareyash05** [comment]
@sairish2001 Resolved merge conflicts

**Review by sairish2001 — CHANGES_REQUESTED** [review]
You deleted some id's from openit function.
Recover them

**Comment by khareyash05** [comment]
@sairish2001 Recovered the lost id's
Sorry

**Review by sairish2001 — CHANGES_REQUESTED** [review]
your id i.e. `#ip` is not present in openit ()

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
