### PR TITLE
Sumofsquare

### LINKED ISSUE #1190: Sum of Squares of given number
This calculator would use the computational formula SS = ΣX2 - ((ΣX)2 / N) - to calculate the sum of squares for a single set of scores.

Just add your scores into the input section and hit Calculate.

### PR DESCRIPTION
**Pull request by shrishti-c**
closes #1190 

Screenshot (202)
Screenshot (203)
Screenshot (204)
Screenshot (205)

### CODE REVIEW

**Comment by sairish2001** [comment]
All the PR's you made, showing same changes along with the actual PR requirement, Kindly review it

**Comment by shrishti-c** [comment]
Screenshot (222)
Screenshot (223)

**Comment by shrishti-c** [comment]
Screenshot (224)
Screenshot (225)

**Comment by shrishti-c** [comment]
@sairish2001  Actually that might seem to be because of branching in git that every new PR includes previous commits too but in actual every PR got one feature extra. I have added the screenshots. The last commits are different in each PR. Since PR was not getting merged, and I had to complete it before deadline, so I opted for branching. :)

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
