### PR TITLE
added new shape in calcutator of 3 D  shapes

### PR DESCRIPTION
**Pull request by supriyagahoi**
Fixed the issue #900  Added new  feature of new type of 3 D shape torus to calculator of  3D shapes  In the section of Graph and shape. And calculated the volume and total surface area of it.

### CODE REVIEW

**Comment by sairish2001** [comment]
Why it's showing 200+ deletion?

**Comment by supriyagahoi** [comment]
It is nothing!! i had added 3 more feature but then i only come up with  adding shape  only and i  other  feature  that  i made  is removed  by me  . I had not deleted any thing from source code  i only add the feature .

**Comment by sairish2001** [comment]
Why you made changes into `function divisionwithsteps() { }` ?

**Comment by supriyagahoi** [comment]
correction is made

**Review by sairish2001 — APPROVED** [review]
Well Done :)

**Pull request merged**
