### PR TITLE
conflict resolve

### PR DESCRIPTION
**Pull request by nidhivanjare**
added operations on a fraction

## Related Issues

- Addition of fractions
- Subtraction of fractions
- Division of fractions
- Multiplication of fractions
- Conversion of the mixed fraction to improper fraction
- Conversion of the improper fraction to mixed fraction

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by sairish2001 — COMMENTED** [review]
Your codebase is outdated, kindly update your code in local machine and make required changes,
It seems your code will create problem, when I merge it

**Comment by nidhivanjare** [comment]
Hey now I have merged the upstream.

**Review by sairish2001 — APPROVED** [review]
Great Work :)
Well Done!

**Comment by sairish2001** [comment]
I just checked the working.
Really Appreciated :)

**Pull request merged**
