### PR TITLE
Rectified Square calculator working over negative values

### PR DESCRIPTION
**Pull request by SarthakKeshari**
## Related Issuse

- Rectified Shape calculator working over negative values

Closes: #[issue number that will be closed through this PR]

#### Made the code work for positive values and propt user in case of negative values entered

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot**
negative values
 | <b>updated screenshot </b> 
Rectified negative values
|

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
Kindly notify if changes are acceptable

**Comment by SarthakKeshari** [comment]
I have made changes for square only if you find it feasible i will work further over rectifying all shapes calculation

**Comment by SarthakKeshari** [comment]
Keeping in mind that length of side can't be negative and also making the user aware of the same I have made the changes

**Review by sairish2001 — APPROVED** [review]
Great Work :)

**Comment by sairish2001** [comment]
You must not create a PR, before assignment of issue.

Follow the ethics of Open Source. Thanks

**Comment by SarthakKeshari** [comment]
I will make sure to follow the ethics of Open Source. This is my first contribution on Github so I couldn't figure out what steps to follow

**Comment by sairish2001** [comment]
Firstly Congratulations on you first PR being merged.

Secondly, Feel free to ask your doubts,if any.

**Pull request merged**
