### PR TITLE
Mean calculator added(AM, GM and HM)

### PR DESCRIPTION
**Pull request by RaveenaBhasin**
This PR is related with issue #447

### CODE REVIEW

**Comment by shrey27tri01** [comment]
Could you please add some screenshots or a short gif or screencast showing the work you did? That'll be useful for future reference :)

**Comment by RaveenaBhasin** [comment]
Screenshot (1548)

**Comment by RaveenaBhasin** [comment]
@shrey27tri01 @sairish2001 I have attached the screenshot

**Comment by sairish2001** [comment]
use LaTex for displaying formulas

**Review by sairish2001 — CHANGES_REQUESTED** [review]
use LaTex for displaying formulas

**Comment by RaveenaBhasin** [comment]
@sairish2001 I have added the formula using latex

**Pull request merged**
