### PR TITLE
Fixed all bug

### LINKED ISSUE #1607: Many buttons in the section Binary Calculation and Probability are not working
## **Describe the bug**

Many buttons in the section Binary Calculation and Probability are not working

## **Possible solution**

one div is not closed

### PR DESCRIPTION
**Pull request by abhijeet141**
## Related Issuse

fix #1607

#### Describe the changes you've made

One div was not closed in index.html and semicolon was not closed in complexlogic.js and added nth term of hp in AP,GP,HP section

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by abhijeet141** [comment]
@sairish2001 Resolved all conflicts :)

**Review by sairish2001 — CHANGES_REQUESTED** [review]
I think you have deleted the harmonic progression nth term part

**Comment by abhijeet141** [comment]
@sairish2001 actually its button was removed so i moved it to its right place i have deleted it and added in Sum of nth term of AP,GP,HP

**Comment by abhijeet141** [comment]
@sairish2001 
image

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
